version: '3.8'

services:
  taskbot-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskbot_dev
    restart: always
    env_file:
      - .env
    volumes:
      - /root/taskbot/states/:/app/persistence/states