version: '3.8'

services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /ara/src/persistence
    env_file:
      - .env
    command: ["alembic", "-c", "alembic.ini", "upgrade", "head"]
    networks:
      - external-net

  arabot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ${STATE_DIR}:/ara/src/persistence/states
    networks:
      - external-net

networks:
  external-net:
    external: true
