version: '3.8'

services:
  arabot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arabot
    restart: always
    env_file:
      - .env
    volumes:
      - /root/taskbot/states/:/app/persistence/states