"""empty message

Revision ID: 228f3b957048
Revises: c67cb4b94656
Create Date: 2026-05-01 15:03:15.304379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228f3b957048'
down_revision: Union[str, None] = 'c67cb4b94656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
