"""empty message

Revision ID: 2a77a882984c
Revises: 580bbdcd67a7
Create Date: 2026-04-18 15:47:40.985925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a77a882984c'
down_revision: Union[str, None] = '580bbdcd67a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('sent_to_model', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'sent_to_model')
    # ### end Alembic commands ###
