"""empty message

Revision ID: 3cd9e98d243b
Revises: 99989a088a3f
Create Date: 2026-04-19 22:09:54.580771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd9e98d243b'
down_revision: Union[str, None] = '99989a088a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('notified', sa.Boolean(), nullable=True))
    op.drop_column('tasks', 'sent_to_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('sent_to_model', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'notified')
    # ### end Alembic commands ###
