"""empty message

Revision ID: 3f6876d132ec
Revises: b85fa19c4a60
Create Date: 2026-04-21 20:22:57.854603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6876d132ec'
down_revision: Union[str, None] = 'b85fa19c4a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('role', sa.String(length=100), nullable=True))
    op.alter_column('messages', 'message', new_column_name='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'role')
    op.alter_column('messages', 'content', new_column_name='message')
    
    # ### end Alembic commands ###
