"""empty message

Revision ID: 3f949495b228
Revises: 7c0c1a89ce1e
Create Date: 2026-04-17 16:56:03.977264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f949495b228'
down_revision: Union[str, None] = '7c0c1a89ce1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'intent')
    op.drop_column('messages', 'state')
    op.drop_column('messages', 'collected_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('collected_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('intent', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
