"""empty message

Revision ID: 619793fc0a07
Revises: 1217594cb96e
Create Date: 2026-04-19 00:47:37.625037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '619793fc0a07'
down_revision: Union[str, None] = '1217594cb96e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('instructions', sa.Text(), nullable=True))
    op.alter_column('users', 'data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               postgresql_using='data::json',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('users', 'instructions')
    # ### end Alembic commands ###
