"""empty message

Revision ID: 7c0c1a89ce1e
Revises: bb0d705f589a
Create Date: 2026-04-17 16:41:36.059479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0c1a89ce1e'
down_revision: Union[str, None] = 'bb0d705f589a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('intent', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('collected_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'collected_data')
    op.drop_column('messages', 'state')
    op.drop_column('messages', 'intent')
    # ### end Alembic commands ###
