"""empty message

Revision ID: 955509b4baba
Revises: 93071d85096d
Create Date: 2026-04-15 15:00:09.876599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '955509b4baba'
down_revision: Union[str, None] = '93071d85096d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('states')
    op.drop_table('plugins')
    op.add_column('tasks', sa.Column('dtend', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('tasks', 'summary',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('tasks', 'message_id')
    op.drop_column('tasks', 'archived')
    op.drop_column('tasks', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('archived', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('tasks', 'summary',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('tasks', 'dtend')
    op.create_table('plugins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('command', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('emoji', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('plugins_pkey'))
    )
    op.create_table('states',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conversation_state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('conversation_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('states_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('states_pkey'))
    )
    op.drop_table('chats')
    # ### end Alembic commands ###
