"""empty message

Revision ID: c67cb4b94656
Revises: d64244b28ff7
Create Date: 2026-04-30 22:38:17.947406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67cb4b94656'
down_revision: Union[str, None] = 'd64244b28ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'notification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('notification', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
