"""empty message

Revision ID: d64244b28ff7
Revises: 5519f3236e67
Create Date: 2026-04-28 16:15:33.808773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd64244b28ff7'
down_revision: Union[str, None] = '5519f3236e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('rrule_human', sa.String(length=255), nullable=True))
    op.alter_column('tasks', 'rrule',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'rrule',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('tasks', 'rrule_human')
    # ### end Alembic commands ###
