# Generated by Django 4.2.2 on 2025-04-03 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tag_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='tag',
            field=models.ManyToManyField(related_name='resource_tags', to='tasks.tag'),
        ),
        migrations.AlterField(
            model_name='resourcelog',
            name='parity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.resourcelog'),
        ),
        migrations.AlterField(
            model_name='resourcelog',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.resource'),
        ),
        migrations.AlterField(
            model_name='resourcelog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.parent'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(related_name='taks_tags', to='tasks.tag'),
        ),
    ]
