# Generated by Django 4.2.2 on 2025-05-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_resource_tag_alter_resourcelog_parity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelog',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourcelog',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcelog',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(related_name='task_tags', to='tasks.tag'),
        ),
    ]
