# Generated by Django 4.2.2 on 2025-05-04 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_resourcelog_completed_resourcelog_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due',
        ),
        migrations.AlterField(
            model_name='parent',
            name='project',
            field=models.ForeignKey(default=6501822403, on_delete=django.db.models.deletion.CASCADE, to='tasks.project'),
        ),
    ]
