# Generated by Django 4.2.2 on 2025-05-09 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_due_alter_parent_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='expiry_modified',
        ),
    ]
