# Generated by Django 4.2.2 on 2025-05-09 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_resource_expiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tasks.resource')),
            ],
        ),
    ]
