# Generated by Django 4.2.2 on 2025-05-11 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_resourceprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='min_pantry',
        ),
    ]
