# Generated by Django 4.2.2 on 2025-05-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_resource_min_pantry'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='default_parity',
            field=models.BooleanField(default=False),
        ),
    ]
