# Generated by Django 4.2.2 on 2025-05-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_resource_default_parity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='default_parity',
        ),
        migrations.RemoveField(
            model_name='resourcelog',
            name='parity',
        ),
        migrations.AddField(
            model_name='resourceprice',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resourceprice',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
