# Generated by Django 4.2.2 on 2025-05-31 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_unit_remove_resource_default_parity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
