# Generated by Django 4.2.2 on 2025-05-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_delete_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceprice',
            name='unit',
        ),
    ]
