# Generated by Django 4.2.2 on 2025-05-31 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_resourceprice_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceprice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 31, 12, 12, 28, 255997, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resourceprice',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
