# Generated by Django 4.2.2 on 2025-05-31 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_resourceprice_date_alter_resourceprice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceprice',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
