# Generated by Django 4.2.2 on 2025-06-02 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_resourceprice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceprice',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='resourceprice',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='tasks.resource'),
        ),
    ]
