# Generated by Django 4.2.2 on 2025-06-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_resourceprice_amount_alter_resourceprice_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceprice',
            name='brand',
        ),
        migrations.AlterField(
            model_name='resource',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='tasks.tag'),
        ),
    ]
