# Generated by Django 4.2.2 on 2025-06-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_remove_resourceprice_brand_alter_resource_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='ttype',
        ),
    ]
