# Generated by Django 4.2.2 on 2025-06-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_remove_tag_ttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tag',
        ),
    ]
