# Generated by Django 4.2.2 on 2025-06-06 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_remove_task_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcelog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.task'),
        ),
    ]
