# Generated by Django 4.2.2 on 2025-07-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_resourcelog_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelog',
            name='temp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
