# Generated by Django 4.2.2 on 2025-07-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_resourcelog_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcelog',
            name='temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
