# Generated by Django 4.2.2 on 2025-10-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_resource_category_resource_code_resource_parity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceprice',
            name='amount',
        ),
    ]
