# Generated by Django 4.2.2 on 2025-10-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_remove_resourceprice_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='code',
        ),
    ]
