# Generated by Django 4.2.2 on 2025-10-15 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_remove_resource_category_remove_resource_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='parity',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='parity_unit',
        ),
        migrations.CreateModel(
            name='ResourceParity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('unit', models.TextField(blank=True, max_length=300, null=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tasks.resource')),
            ],
        ),
    ]
