# Generated by Django 4.2.2 on 2025-10-15 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_remove_resource_parity_remove_resource_parity_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceparity',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parity', to='tasks.resource'),
        ),
    ]
