# Generated by Django 4.2.2 on 2025-10-17 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_alter_resourceparity_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourceparity',
            old_name='unit',
            new_name='consumption_unit',
        ),
        migrations.RenameField(
            model_name='resourceparity',
            old_name='amount',
            new_name='conversion_factor',
        ),
    ]
