# Generated by Django 4.2.2 on 2025-10-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_rename_unit_resourceparity_consumption_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='unit',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='resourceparity',
            name='consumption_unit',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
