# Generated by Django 4.2.2 on 2025-10-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_alter_resource_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcelog',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourceparity',
            name='conversion_factor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
