# Generated by Django 4.2.2 on 2025-10-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_alter_resourcelog_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='min_pantry',
            field=models.IntegerField(default=0),
        ),
    ]
