# Generated by Django 4.2.2 on 2025-10-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_resource_min_pantry'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelog',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
