# Generated by Django 4.2.2 on 2025-10-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_resourcelog_skipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
