# Generated by Django 4.2.2 on 2025-10-31 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_task_skipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcelog',
            name='temp',
        ),
    ]
